### ISSUE TITLE
Fix Frame skips at beginning of game

### ISSUE THREAD

**Issue by jsmli** [UCSB-CS56-Projects/cs56-android-games-slingy-ball#16]
There seems to always be one or two frame skips when the game starts up on my OP3. This may occur on other devices as well.

Associated error message:
I/Choreographer: Skipped 52 frames!  The application may be doing too much work on its main thread.

**Comment by joelbagan** [comment]
This seems like more of a bug fix/optimization that neither breaks the game significantly, nor affects the overall user experience significantly. That said, it is good practice to make your activity initialization as clean and quick as possible.
