### ISSUE TITLE
Leaderboard (local)

### ISSUE THREAD

**Issue by joelbagan** [UCSB-CS56-Projects/cs56-android-games-slingy-ball#7]
Implement a leaderboard of high scores that are locally stored. Allow for users to input a name for their score, and view the leaderboard from a menu.

F17 OK (50pts)

**Comment by jsmli** [comment]
Score must be implemented first

**Comment by jsmli** [comment]
Can we just store 1 high score instead? It doesn't really make for a local leaderboard to include more than 1 person, since this is a mobile game, not an arcade game.
